In [36]:

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
from sqlalchemy import create_engine
from pprint import pprint
from config import ODMb_api_key
import json
key="342919475fdd9494b35f7a36b0bae916"

In [37]:

url_list = []


for i in range(1, 100):
    num = i
    url = "https://api.themoviedb.org/3/movie/popular?api_key="+key+"&language=en-US&page=" + str(num)
    url_list.append(url)

    
print(url_list)

['https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=1', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=2', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=3', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=4', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=5', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=6', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=7', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=8', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=9', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=10', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=11', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=12', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=13', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=14', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=15', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=16', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=17', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=18', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=19', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=20', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=21', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=22', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=23', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=24', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=25', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=26', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=27', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=28', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=29', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=30', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=31', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=32', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=33', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=34', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=35', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=36', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=37', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=38', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=39', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=40', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=41', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=42', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=43', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=44', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=45', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=46', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=47', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=48', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=49', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=50', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=51', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=52', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=53', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=54', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=55', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=56', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=57', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=58', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=59', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=60', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=61', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=62', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=63', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=64', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=65', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=66', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=67', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=68', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=69', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=70', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=71', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=72', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=73', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=74', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=75', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=76', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=77', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=78', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=79', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=80', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=81', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=82', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=83', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=84', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=85', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=86', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=87', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=88', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=89', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=90', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=91', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=92', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=93', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=94', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=95', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=96', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=97', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=98', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=99']

In [38]:
print(key)

342919475fdd9494b35f7a36b0bae916

In [39]:

def query_api(car):
    r = requests.get(car)
    info = r.json()
    return info['results']


movies_list = []

for i in url_list:
    r = query_api(i)    
    movies_list.append(r)

In [40]:
m_list = []

for i in range(len(movies_list)):
    for j in range(20):
        m_list.append(movies_list[i][j].items())
        
        #mymovies_df = pd.DataFrame(m_list)
        
        #m_list = m_list.split(',')
        
        #print(m_list)

In [41]:
 mymovies_df = pd.DataFrame(m_list)

In [42]:
mymovies_df.head(100)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,"(popularity, 533.832)","(vote_count, 1707)","(video, False)","(poster_path, /db32LaOibwEliAmSL2jjDF6oDdj.jpg)","(id, 181812)","(adult, False)","(backdrop_path, /jOzrELAzFxtMx2I4uDGHOotdfsS.jpg)","(original_language, en)","(original_title, Star Wars: The Rise of Skywal...","(genre_ids, [28, 12, 878])","(title, Star Wars: The Rise of Skywalker)","(vote_average, 6.7)","(overview, The surviving Resistance faces the ...","(release_date, 2019-12-18)"
1,"(popularity, 498.196)","(vote_count, 1586)","(video, False)","(poster_path, /xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg)","(id, 419704)","(adult, False)","(backdrop_path, /p3TCqUDoVsrIm8fHK9KOTfWnDjZ.jpg)","(original_language, en)","(original_title, Ad Astra)","(genre_ids, [12, 18, 9648, 878, 53])","(title, Ad Astra)","(vote_average, 6)","(overview, The near future, a time when both h...","(release_date, 2019-09-17)"
2,"(popularity, 356.371)","(vote_count, 738)","(video, False)","(poster_path, /jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg)","(id, 512200)","(adult, False)","(backdrop_path, /zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg)","(original_language, en)","(original_title, Jumanji: The Next Level)","(genre_ids, [28, 12, 35, 14])","(title, Jumanji: The Next Level)","(vote_average, 6.8)","(overview, As the gang return to Jumanji to re...","(release_date, 2019-12-04)"
3,"(popularity, 254.937)","(vote_count, 7172)","(video, False)","(poster_path, /udDclJoHjfjb8Ekgsd4FDteOkCU.jpg)","(id, 475557)","(adult, False)","(backdrop_path, /n6bUvigpRFqSwmPp1m2YADdbRBc.jpg)","(original_language, en)","(original_title, Joker)","(genre_ids, [80, 18, 53])","(title, Joker)","(vote_average, 8.3)","(overview, During the 1980s, a failed stand-up...","(release_date, 2019-10-02)"
4,"(popularity, 240.111)","(vote_count, 80)","(video, False)","(poster_path, /yJdeWaVXa2se9agI6B4mQunVYkB.jpg)","(id, 449924)","(adult, False)","(backdrop_path, /ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg)","(original_language, cn)","(original_title, 葉問4)","(genre_ids, [28, 18, 36])","(title, Ip Man 4: The Finale)","(vote_average, 6.2)","(overview, Following the death of his wife, Ip...","(release_date, 2019-12-20)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"(popularity, 47.656)","(vote_count, 31)","(video, False)","(poster_path, /3cn0FmkBPu6KzN2SQM0k2JfPvkB.jpg)","(id, 530915)","(adult, False)","(backdrop_path, /ds9GKAMhxv5AbprmZ2xCpK8FiEG.jpg)","(original_language, en)","(original_title, 1917)","(genre_ids, [18, 36, 10752])","(title, 1917)","(vote_average, 7.6)","(overview, At the height of the First World Wa...","(release_date, 2019-12-10)"
96,"(popularity, 39.28)","(vote_count, 12608)","(video, False)","(poster_path, /fTplI1NCSuEDP4ITLcTps739fcC.jpg)","(id, 12445)","(adult, False)","(backdrop_path, /n5A7brJCjejceZmHyujwUTVgQNC.jpg)","(original_language, en)","(original_title, Harry Potter and the Deathly ...","(genre_ids, [12, 14])","(title, Harry Potter and the Deathly Hallows: ...","(vote_average, 8.1)","(overview, Harry, Ron and Hermione continue th...","(release_date, 2011-07-07)"
97,"(popularity, 47.893)","(vote_count, 1887)","(video, False)","(poster_path, /fQ40gmFM4p03tXwMxQQKh2cCBW4.jpg)","(id, 373571)","(adult, False)","(backdrop_path, /cNt14e43I2DDW6Xd9zFhrP8eOcA.jpg)","(original_language, en)","(original_title, Godzilla: King of the Monsters)","(genre_ids, [28, 878])","(title, Godzilla: King of the Monsters)","(vote_average, 6.1)","(overview, Follows the heroic efforts of the c...","(release_date, 2019-05-29)"
98,"(popularity, 47.866)","(id, 812)","(video, False)","(vote_count, 7208)","(vote_average, 7.6)","(title, Aladdin)","(release_date, 1992-11-25)","(original_language, en)","(original_title, Aladdin)","(genre_ids, [16, 10751, 12, 14, 10749])","(backdrop_path, /5OeY4U2rzePxWq2rkqMajUx2gz7.jpg)","(adult, False)","(overview, Princess Jasmine grows tired of bei...","(poster_path, /mjKozYRuHc9j7SmiXmbVmCiAM0A.jpg)"
99,"(popularity, 94.501)","(vote_count, 7403)","(video, False)","(poster_path, /9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg)","(id, 260513)","(adult, False)","(backdrop_path, /mabuNsGJgRuCTuGqjFkWe1xdu19.jpg)","(original_language, en)","(original_title, Incredibles 2)","(genre_ids, [28, 12, 16, 10751])","(title, Incredibles 2)","(vote_average, 7.5)","(overview, Elastigirl springs into action to s...","(release_date, 2018-06-14)"

In [43]:
cols = []
for col in mymovies_df.columns:
    col = str(col)
    cols.append(col.lower())
mymovies_df.columns = cols
cols

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13']

In [44]:
mymovies_df =mymovies_df.rename(columns = {'0': 'popularity', '1': 'vote_count', '2': 'video' , '3': 'poster_path', '4': 'id' , '5': 'adult' , '6': 'backdrop_path' , '7': 'original_language', '8': 'original_title', '9': 'genre_ids' , '10': 'title' , '11': 'vote_average' , '12': 'overview' , '13': 'release_date'})

In [45]:
mymovies_df

,popularity,vote_count,video,poster_path,id,adult,backdrop_path,original_language,original_title,genre_ids,title,vote_average,overview,release_date
0,"(popularity, 533.832)","(vote_count, 1707)","(video, False)","(poster_path, /db32LaOibwEliAmSL2jjDF6oDdj.jpg)","(id, 181812)","(adult, False)","(backdrop_path, /jOzrELAzFxtMx2I4uDGHOotdfsS.jpg)","(original_language, en)","(original_title, Star Wars: The Rise of Skywal...","(genre_ids, [28, 12, 878])","(title, Star Wars: The Rise of Skywalker)","(vote_average, 6.7)","(overview, The surviving Resistance faces the ...","(release_date, 2019-12-18)"
1,"(popularity, 498.196)","(vote_count, 1586)","(video, False)","(poster_path, /xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg)","(id, 419704)","(adult, False)","(backdrop_path, /p3TCqUDoVsrIm8fHK9KOTfWnDjZ.jpg)","(original_language, en)","(original_title, Ad Astra)","(genre_ids, [12, 18, 9648, 878, 53])","(title, Ad Astra)","(vote_average, 6)","(overview, The near future, a time when both h...","(release_date, 2019-09-17)"
2,"(popularity, 356.371)","(vote_count, 738)","(video, False)","(poster_path, /jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg)","(id, 512200)","(adult, False)","(backdrop_path, /zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg)","(original_language, en)","(original_title, Jumanji: The Next Level)","(genre_ids, [28, 12, 35, 14])","(title, Jumanji: The Next Level)","(vote_average, 6.8)","(overview, As the gang return to Jumanji to re...","(release_date, 2019-12-04)"
3,"(popularity, 254.937)","(vote_count, 7172)","(video, False)","(poster_path, /udDclJoHjfjb8Ekgsd4FDteOkCU.jpg)","(id, 475557)","(adult, False)","(backdrop_path, /n6bUvigpRFqSwmPp1m2YADdbRBc.jpg)","(original_language, en)","(original_title, Joker)","(genre_ids, [80, 18, 53])","(title, Joker)","(vote_average, 8.3)","(overview, During the 1980s, a failed stand-up...","(release_date, 2019-10-02)"
4,"(popularity, 240.111)","(vote_count, 80)","(video, False)","(poster_path, /yJdeWaVXa2se9agI6B4mQunVYkB.jpg)","(id, 449924)","(adult, False)","(backdrop_path, /ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg)","(original_language, cn)","(original_title, 葉問4)","(genre_ids, [28, 18, 36])","(title, Ip Man 4: The Finale)","(vote_average, 6.2)","(overview, Following the death of his wife, Ip...","(release_date, 2019-12-20)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975,"(popularity, 11.538)","(vote_count, 717)","(video, False)","(poster_path, /2h2mThLae2QZLprtovKXRBgMM1E.jpg)","(id, 1266)","(adult, False)","(backdrop_path, /vQL3dus5e8XtpAiJKFcI8YiITlV.jpg)","(original_language, en)","(original_title, Street Kings)","(genre_ids, [28, 80, 18, 53])","(title, Street Kings)","(vote_average, 6.5)","(overview, Tom Ludlow is a disillusioned L.A. ...","(release_date, 2008-04-10)"
1976,"(popularity, 15.97)","(vote_count, 1392)","(video, False)","(poster_path, /xVuBEKHqzIC6DRuVfjdt2306crQ.jpg)","(id, 192141)","(adult, False)","(backdrop_path, /l97RWqhhZnrCjb2xQ5ZCGveQkq1.jpg)","(original_language, en)","(original_title, No Escape)","(genre_ids, [28, 53])","(title, No Escape)","(vote_average, 6.8)","(overview, In their new overseas home, an Amer...","(release_date, 2015-08-26)"
1977,"(popularity, 12.433)","(vote_count, 2251)","(video, False)","(poster_path, /xiL4PMdL2b5RRdsfEkGmaol2ScW.jpg)","(id, 3981)","(adult, False)","(backdrop_path, /hUCf8nuuSjUwWlOmTVVPXJHl97v.jpg)","(original_language, en)","(original_title, What Women Want)","(genre_ids, [35, 10749])","(title, What Women Want)","(vote_average, 6.3)","(overview, Advertising executive Nick Marshall...","(release_date, 2000-12-15)"
1978,"(popularity, 13.495)","(vote_count, 2434)","(video, False)","(poster_path, /gkkiDu9srCCbCMxGKwNwKCxK7KF.jpg)","(id, 72976)","(adult, False)","(backdrop_path, /9vZzjmaXIYotKGnCfQyWBD7PAIO.jpg)","(original_language, en)","(original_title, Lincoln)","(genre_ids, [18, 36])","(title, Lincoln)","(vote_average, 6.8)","(overview, The revealing story of the 16th US ...","(release_date, 2012-11-09)"
1979,"(popularity, 11.778)","(vote_count, 1065)","(video, False)","(poster_path, /wNUAnXV1mzOOfvnVBIYsalkk078.jpg)","(id, 11978)","(adult, False)","(backdrop_path, /7wVtInOyDrYlcZGQcaGGH4rm8iJ.jpg)","(original_language, en)","(original_title, Men of Honor)","(genre_ids, [18])","(title, Men of Honor)","(vote_average, 7.2)","(overview, Against formidable odds -- and an o...","(release_date, 2000-09-13)"

In [46]:
pop_col_df = pd.DataFrame(mymovies_df['popularity'].tolist(), index=mymovies_df.index)

pop_col_df = pop_col_df.drop([0], axis=1)

pop_col_df = pop_col_df.rename(columns = {1 : "popularity"})

# pop_col_df

In [47]:

    
vote_count_df = pd.DataFrame(mymovies_df['vote_count'].tolist(), index=mymovies_df.index)

vote_count_df = vote_count_df.drop([0], axis=1)

vote_count_df = vote_count_df.rename(columns = {1 : "vote_count"})
    
# vote_count_df

In [48]:

video_df = pd.DataFrame(mymovies_df['video'].tolist(), index=mymovies_df.index)

video_df = video_df.drop([0], axis=1)

video_df = video_df.rename(columns = {1 : "video"})
    
    
# video_df

In [49]:

    
    
poster_path_df = pd.DataFrame(mymovies_df['poster_path'].tolist(), index=mymovies_df.index)

poster_path_df = poster_path_df.drop([0], axis=1)
    
poster_path_df = poster_path_df.rename(columns = {1 : "poster_path"})


# poster_path_df

In [50]:


id_df = pd.DataFrame(mymovies_df['id'].tolist(), index=mymovies_df.index)

id_df = id_df.drop([0], axis=1)

id_df = id_df.rename(columns = {1 : "id"})

# id_df

In [51]:


adult_df = pd.DataFrame(mymovies_df['adult'].tolist(), index=mymovies_df.index)

adult_df = adult_df.drop([0], axis=1)

adult_df = adult_df.rename(columns = {1 : "adult"})

# adult_df
    
# adult_df.replace(['Joker', 'Star Wars'], False, inplace=True)

In [52]:


backdrop_path_df = pd.DataFrame(mymovies_df['backdrop_path'].tolist(), index=mymovies_df.index)

backdrop_path_df =  backdrop_path_df.drop([0], axis=1)

backdrop_path_df = backdrop_path_df.rename(columns = {1 : "backdrop_path"})

# backdrop_path_df
    
# backdrop_path_df = backdrop_path_df.rename(columns = {0 : "original_language"}

In [53]:


original_language_df = pd.DataFrame(mymovies_df['original_language'].tolist(), index=mymovies_df.index)

original_language_df =  original_language_df.drop([0], axis=1)

original_language_df = original_language_df.rename(columns = {1 : "original_language"})

# original_language_df
    
# original_language_df = original_language_df.rename(columns = {0 : "original_language"}

In [54]:


original_title_df = pd.DataFrame(mymovies_df['original_title'].tolist(), index=mymovies_df.index)

original_title_df =  original_title_df.drop([0], axis=1)

original_title_df = original_title_df.rename(columns = {1 : "original_title"})

# original_title_df

In [55]:


title_df = pd.DataFrame(mymovies_df['title'].tolist(), index=mymovies_df.index)

title_df  =  title_df.drop([0], axis=1)

title_df = title_df.rename(columns = {1 : "title"})

# title_df

In [56]:

    
#     vote_average_df = vote_average_df.rename(columns = {0 : "vote_average"})
    
#     vote_average_df.replace(['Joker', 'Star Wars'], False, inplace=True)
    
#     vote_average_df.replace( False, np.nan, inplace=True)
    
    
    
    
vote_average_df = pd.DataFrame(mymovies_df['vote_average'].tolist(), index=mymovies_df.index)

vote_average_df =  vote_average_df.drop([0], axis=1)

vote_average_df = vote_average_df.rename(columns = {1 : "vote_average"})

# vote_average_df

In [57]:


overview_df = pd.DataFrame(mymovies_df['overview'].tolist(), index=mymovies_df.index)

overview_df =  overview_df.drop([0], axis=1)

overview_df = overview_df.rename(columns = {1 : "overview"})

overview_df

                                               overview
0     The surviving Resistance faces the First Order...
1     The near future, a time when both hope and har...
2     As the gang return to Jumanji to rescue one of...
3     During the 1980s, a failed stand-up comedian i...
4     Following the death of his wife, Ip Man travel...
...                                                 ...
1975  Tom Ludlow is a disillusioned L.A. Police Offi...
1976  In their new overseas home, an American family...
1977  Advertising executive Nick Marshall is as cock...
1978  The revealing story of the 16th US President's...
1979  Against formidable odds -- and an old-school d...

[1980 rows x 1 columns]

In [58]:
release_date_df = pd.DataFrame(mymovies_df['release_date'].tolist(), index=mymovies_df.index)

release_date_df =  release_date_df.drop([0], axis=1)

release_date_df = release_date_df.rename(columns = {1 : "release_date"})

release_date_df

     release_date
0      2019-12-18
1      2019-09-17
2      2019-12-04
3      2019-10-02
4      2019-12-20
...           ...
1975   2008-04-10
1976   2015-08-26
1977   2000-12-15
1978   2012-11-09
1979   2000-09-13

[1980 rows x 1 columns]

In [59]:
# release_date_df.replace('/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg', '2019-10-02', inplace=True)

# release_date_df.replace('/btTdmkgIvOi0FFip1sPuZI2oQG6.jpg', '1977-05-25', inplace=True)

In [60]:
movie_results = pd.concat([pop_col_df, vote_count_df, video_df, poster_path_df, id_df, adult_df, backdrop_path_df, original_language_df, 
                    original_title_df, title_df, vote_average_df, overview_df, release_date_df], axis = 1)

In [61]:
movie_results

,popularity,vote_count,video,poster_path,id,adult,backdrop_path,original_language,original_title,title,vote_average,overview,release_date
0,533.832,1707,False,/db32LaOibwEliAmSL2jjDF6oDdj.jpg,181812,False,/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg,en,Star Wars: The Rise of Skywalker,Star Wars: The Rise of Skywalker,6.7,The surviving Resistance faces the First Order...,2019-12-18
1,498.196,1586,False,/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg,419704,False,/p3TCqUDoVsrIm8fHK9KOTfWnDjZ.jpg,en,Ad Astra,Ad Astra,6,"The near future, a time when both hope and har...",2019-09-17
2,356.371,738,False,/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg,512200,False,/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg,en,Jumanji: The Next Level,Jumanji: The Next Level,6.8,As the gang return to Jumanji to rescue one of...,2019-12-04
3,254.937,7172,False,/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg,475557,False,/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg,en,Joker,Joker,8.3,"During the 1980s, a failed stand-up comedian i...",2019-10-02
4,240.111,80,False,/yJdeWaVXa2se9agI6B4mQunVYkB.jpg,449924,False,/ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg,cn,葉問4,Ip Man 4: The Finale,6.2,"Following the death of his wife, Ip Man travel...",2019-12-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975,11.538,717,False,/2h2mThLae2QZLprtovKXRBgMM1E.jpg,1266,False,/vQL3dus5e8XtpAiJKFcI8YiITlV.jpg,en,Street Kings,Street Kings,6.5,Tom Ludlow is a disillusioned L.A. Police Offi...,2008-04-10
1976,15.970,1392,False,/xVuBEKHqzIC6DRuVfjdt2306crQ.jpg,192141,False,/l97RWqhhZnrCjb2xQ5ZCGveQkq1.jpg,en,No Escape,No Escape,6.8,"In their new overseas home, an American family...",2015-08-26
1977,12.433,2251,False,/xiL4PMdL2b5RRdsfEkGmaol2ScW.jpg,3981,False,/hUCf8nuuSjUwWlOmTVVPXJHl97v.jpg,en,What Women Want,What Women Want,6.3,Advertising executive Nick Marshall is as cock...,2000-12-15
1978,13.495,2434,False,/gkkiDu9srCCbCMxGKwNwKCxK7KF.jpg,72976,False,/9vZzjmaXIYotKGnCfQyWBD7PAIO.jpg,en,Lincoln,Lincoln,6.8,The revealing story of the 16th US President's...,2012-11-09
1979,11.778,1065,False,/wNUAnXV1mzOOfvnVBIYsalkk078.jpg,11978,False,/7wVtInOyDrYlcZGQcaGGH4rm8iJ.jpg,en,Men of Honor,Men of Honor,7.2,Against formidable odds -- and an old-school d...,2000-09-13

In [62]:
cols = []
for col in movie_results.columns:
    col = str(col)
    cols.append(col.lower())
movie_results.columns = cols
cols

['popularity',
 'vote_count',
 'video',
 'poster_path',
 'id',
 'adult',
 'backdrop_path',
 'original_language',
 'original_title',
 'title',
 'vote_average',
 'overview',
 'release_date']

In [63]:

#rds_connection_string = "postgres:Dbadmin@localhost:5432/ODBM_db"
#engine = create_engine(f'postgresql://{rds_connection_string}')


rds_connection_string = "postgres:Dbadmin@localhost:5432/ODBM_db"
engine = create_engine(f'postgresql://postgres:postgres@localhost/movies')

In [64]:
engine.table_names()

['movies']

In [65]:
movie_results.to_sql(name='movies', con=engine, if_exists='append', index=False)

DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(60)

[SQL: INSERT INTO movies (popularity, vote_count, video, poster_path, id, adult, backdrop_path, original_language, original_title, title, vote_average, overview, release_date) VALUES (%(popularity)s, %(vote_count)s, %(video)s, %(poster_path)s, %(id)s, %(adult)s, %(backdrop_path)s, %(original_language)s, %(original_title)s, %(title)s, %(vote_average)s, %(overview)s, %(release_date)s)]
[parameters: ({'popularity': 533.832, 'vote_count': 1707, 'video': False, 'poster_path': '/db32LaOibwEliAmSL2jjDF6oDdj.jpg', 'id': 181812, 'adult': False, 'backdrop_path': '/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg', 'original_language': 'en', 'original_title': 'Star Wars: The Rise of Skywalker', 'title': 'Star Wars: The Rise of Skywalker', 'vote_average': 6.7, 'overview': 'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.', 'release_date': '2019-12-18'}, {'popularity': 498.196, 'vote_count': 1586, 'video': False, 'poster_path': '/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg', 'id': 419704, 'adult': False, 'backdrop_path': '/p3TCqUDoVsrIm8fHK9KOTfWnDjZ.jpg', 'original_language': 'en', 'original_title': 'Ad Astra', 'title': 'Ad Astra', 'vote_average': 6, 'overview': 'The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy ... (92 characters truncated) ... ace and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.', 'release_date': '2019-09-17'}, {'popularity': 356.371, 'vote_count': 738, 'video': False, 'poster_path': '/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg', 'id': 512200, 'adult': False, 'backdrop_path': '/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg', 'original_language': 'en', 'original_title': 'Jumanji: The Next Level', 'title': 'Jumanji: The Next Level', 'vote_average': 6.8, 'overview': 'As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.', 'release_date': '2019-12-04'}, {'popularity': 254.937, 'vote_count': 7172, 'video': False, 'poster_path': '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg', 'id': 475557, 'adult': False, 'backdrop_path': '/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg', 'original_language': 'en', 'original_title': 'Joker', 'title': 'Joker', 'vote_average': 8.3, 'overview': 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.', 'release_date': '2019-10-02'}, {'popularity': 240.111, 'vote_count': 80, 'video': False, 'poster_path': '/yJdeWaVXa2se9agI6B4mQunVYkB.jpg', 'id': 449924, 'adult': False, 'backdrop_path': '/ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg', 'original_language': 'cn', 'original_title': '葉問4', 'title': 'Ip Man 4: The Finale', 'vote_average': 6.2, 'overview': 'Following the death of his wife, Ip Man travels to San Francisco to ease tensions between the local kung fu masters and his star student, Bruce Lee, while searching for a better future for his son.', 'release_date': '2019-12-20'}, {'popularity': 128.692, 'vote_count': 940, 'video': False, 'poster_path': '/lnWkyG3LLgbbrIEeyl5mK5VRFe4.jpg', 'id': 509967, 'adult': False, 'backdrop_path': '/eFw5YSorHidsajLTayo1noueIxI.jpg', 'original_language': 'en', 'original_title': '6 Underground', 'title': '6 Underground', 'vote_average': 6.2, 'overview': 'After faking his death, a tech billionaire recruits a team of international operatives for a bold and bloody mission to take down a brutal dictator.', 'release_date': '2019-12-13'}, {'popularity': 109.5, 'vote_count': 16194, 'video': False, 'poster_path': '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg', 'id': 299536, 'adult': False, 'backdrop_path': '/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg', 'original_language': 'en', 'original_title': 'Avengers: Infinity War', 'title': 'Avengers: Infinity War', 'vote_average': 8.3, 'overview': 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from ... (192 characters truncated) ... of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.', 'release_date': '2018-04-25'}, {'popularity': 157.334, 'vote_count': 35, 'video': False, 'poster_path': '/eU0orGizEpOli4wtN8HtfOOJDlA.jpg', 'id': 516700, 'adult': False, 'backdrop_path': '/mlaX4c2M6usnhXHG5sYJcKVXflA.jpg', 'original_language': 'id', 'original_title': 'Gundala', 'title': 'Gundala', 'vote_average': 5.5, 'overview': 'Sancaka has lived on the streets since his parents left him. Living a hard life, Sancaka survives by thinking about his own safety. When the conditio ... (30 characters truncated) ... njustice rages throughout the country, Sancaka must decide whether he continues to live to look after himself or rise to become their oppressed hero.', 'release_date': '2019-08-29'}  ... displaying 10 of 1980 total bound parameter sets ...  {'popularity': 13.495, 'vote_count': 2434, 'video': False, 'poster_path': '/gkkiDu9srCCbCMxGKwNwKCxK7KF.jpg', 'id': 72976, 'adult': False, 'backdrop_path': '/9vZzjmaXIYotKGnCfQyWBD7PAIO.jpg', 'original_language': 'en', 'original_title': 'Lincoln', 'title': 'Lincoln', 'vote_average': 6.8, 'overview': "The revealing story of the 16th US President's tumultuous final months in office. In a nation divided by war and the strong winds of change, Lincoln  ... (86 characters truncated) ... ery. With the moral courage and fierce determination to succeed, his choices during this critical moment will change the fate of generations to come.", 'release_date': '2012-11-09'}, {'popularity': 11.778, 'vote_count': 1065, 'video': False, 'poster_path': '/wNUAnXV1mzOOfvnVBIYsalkk078.jpg', 'id': 11978, 'adult': False, 'backdrop_path': '/7wVtInOyDrYlcZGQcaGGH4rm8iJ.jpg', 'original_language': 'en', 'original_title': 'Men of Honor', 'title': 'Men of Honor', 'vote_average': 7.2, 'overview': "Against formidable odds -- and an old-school diving instructor embittered by the U.S. Navy's new, less prejudicial policies -- Carl Brashear sets his ... (100 characters truncated) ... ir relationship starts out on the rocks, but fate ultimately conspires to bring the men together into a setting of mutual respect, triumph and honor.", 'release_date': '2000-09-13'})]
(Background on this error at: http://sqlalche.me/e/9h9h)