In [4]:

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
from sqlalchemy import create_engine
from pprint import pprint
from config import ODMb_api_key
import json
key="342919475fdd9494b35f7a36b0bae916"

In [5]:

url_list = []


for i in range(1, 100):
    num = i
    url = "https://api.themoviedb.org/3/movie/popular?api_key="+key+"&language=en-US&page=" + str(num)
    url_list.append(url)

    
print(url_list)

['https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=1', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=2', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=3', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=4', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=5', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=6', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=7', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=8', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=9', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=10', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=11', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=12', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=13', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=14', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=15', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=16', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=17', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=18', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=19', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=20', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=21', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=22', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=23', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=24', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=25', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=26', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=27', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=28', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=29', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=30', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=31', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=32', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=33', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=34', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=35', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=36', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=37', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=38', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=39', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=40', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=41', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=42', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=43', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=44', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=45', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=46', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=47', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=48', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=49', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=50', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=51', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=52', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=53', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=54', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=55', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=56', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=57', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=58', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=59', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=60', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=61', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=62', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=63', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=64', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=65', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=66', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=67', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=68', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=69', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=70', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=71', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=72', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=73', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=74', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=75', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=76', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=77', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=78', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=79', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=80', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=81', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=82', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=83', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=84', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=85', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=86', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=87', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=88', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=89', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=90', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=91', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=92', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=93', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=94', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=95', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=96', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=97', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=98', 'https://api.themoviedb.org/3/movie/popular?api_key=342919475fdd9494b35f7a36b0bae916&language=en-US&page=99']

In [6]:
print(key)

342919475fdd9494b35f7a36b0bae916

In [7]:

def query_api(car):
    r = requests.get(car)
    info = r.json()
    return info['results']


movies_list = []

for i in url_list:
    r = query_api(i)    
    movies_list.append(r)

In [8]:
m_list = []

for i in range(len(movies_list)):
    for j in range(20):
        m_list.append(movies_list[i][j].items())
        
        #mymovies_df = pd.DataFrame(m_list)
        
        #m_list = m_list.split(',')
        
        #print(m_list)

In [9]:
 mymovies_df = pd.DataFrame(m_list)

In [10]:
mymovies_df.head(100)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,"(popularity, 454.192)","(vote_count, 1229)","(video, False)","(poster_path, /db32LaOibwEliAmSL2jjDF6oDdj.jpg)","(id, 181812)","(adult, False)","(backdrop_path, /dCB7d4l0mfpsISZvr6aPE2z5QF6.jpg)","(original_language, en)","(original_title, Star Wars: The Rise of Skywal...","(genre_ids, [28, 12, 878])","(title, Star Wars: The Rise of Skywalker)","(vote_average, 6.7)","(overview, The surviving Resistance faces the ...","(release_date, 2019-12-18)"
1,"(popularity, 472.09)","(vote_count, 1489)","(video, False)","(poster_path, /xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg)","(id, 419704)","(adult, False)","(backdrop_path, /p3TCqUDoVsrIm8fHK9KOTfWnDjZ.jpg)","(original_language, en)","(original_title, Ad Astra)","(genre_ids, [12, 18, 9648, 878, 53])","(title, Ad Astra)","(vote_average, 6)","(overview, The near future, a time when both h...","(release_date, 2019-09-17)"
2,"(popularity, 341.325)","(vote_count, 56)","(video, False)","(poster_path, /2MwpeDrI7RbgD6bipT31kpMZe9u.jpg)","(id, 449924)","(adult, False)","(backdrop_path, /ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg)","(original_language, cn)","(original_title, 葉問4)","(genre_ids, [28, 18, 36])","(title, Ip Man 4: The Finale)","(vote_average, 6.1)","(overview, Ip Man 4 is an upcoming Hong Kong b...","(release_date, 2019-12-20)"
3,"(popularity, 271.823)","(vote_count, 6940)","(video, False)","(poster_path, /udDclJoHjfjb8Ekgsd4FDteOkCU.jpg)","(id, 475557)","(adult, False)","(backdrop_path, /n6bUvigpRFqSwmPp1m2YADdbRBc.jpg)","(original_language, en)","(original_title, Joker)","(genre_ids, [80, 18, 53])","(title, Joker)","(vote_average, 8.3)","(overview, During the 1980s, a failed stand-up...","(release_date, 2019-10-02)"
4,"(popularity, 280.669)","(vote_count, 551)","(video, False)","(poster_path, /jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg)","(id, 512200)","(adult, False)","(backdrop_path, /zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg)","(original_language, en)","(original_title, Jumanji: The Next Level)","(genre_ids, [28, 12, 35, 14])","(title, Jumanji: The Next Level)","(vote_average, 6.7)","(overview, As the gang return to Jumanji to re...","(release_date, 2019-12-04)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"(popularity, 35.494)","(vote_count, 11347)","(video, False)","(poster_path, /sKCr78MXSLixwmZ8DyJLrpMsd15.jpg)","(id, 8587)","(adult, False)","(backdrop_path, /2wW1hyNxpU36aNtNSHVhIOJccde.jpg)","(original_language, en)","(original_title, The Lion King)","(genre_ids, [16, 18, 10751])","(title, The Lion King)","(vote_average, 8.2)","(overview, A young lion prince is cast out of ...","(release_date, 1994-05-07)"
96,"(popularity, 40.349)","(vote_count, 5182)","(video, False)","(poster_path, /hKHZhUbIyUAjcSrqJThFGYIR6kI.jpg)","(id, 466282)","(adult, False)","(backdrop_path, /uZTtVdOEIwPA6vwVRI3217DoPM.jpg)","(original_language, en)","(original_title, To All the Boys I've Loved Be...","(genre_ids, [35, 10749])","(title, To All the Boys I've Loved Before)","(vote_average, 7.9)","(overview, Lara Jean's love life goes from ima...","(release_date, 2018-08-16)"
97,"(popularity, 37.201)","(vote_count, 3652)","(video, False)","(poster_path, /rtGDOeG9LzoerkDGZF9dnVeLppL.jpg)","(id, 8392)","(adult, False)","(backdrop_path, /hoIqf9YjZM0oQOrFXp8DcucJ3Jg.jpg)","(original_language, ja)","(original_title, となりのトトロ)","(genre_ids, [16, 14, 10751])","(title, My Neighbor Totoro)","(vote_average, 8.1)","(overview, Two sisters move to the country wit...","(release_date, 1988-04-16)"
98,"(popularity, 36.616)","(vote_count, 8201)","(video, False)","(poster_path, /oRvMaJOmapypFUcQqpgHMZA6qL9.jpg)","(id, 129)","(adult, False)","(backdrop_path, /mnpRKVSXBX6jb56nabvmGKA0Wig.jpg)","(original_language, ja)","(original_title, 千と千尋の神隠し)","(genre_ids, [16, 14, 10751])","(title, Spirited Away)","(vote_average, 8.5)","(overview, A young girl, Chihiro, becomes trap...","(release_date, 2001-07-20)"
99,"(popularity, 33.366)","(vote_count, 8242)","(video, False)","(poster_path, /vfzE3pjE5G7G7kcZWrA3fnbZo7V.jpg)","(id, 78)","(adult, False)","(backdrop_path, /eIi3klFf7mp3oL5EEF4mLIDs26r.jpg)","(original_language, en)","(original_title, Blade Runner)","(genre_ids, [18, 878, 53])","(title, Blade Runner)","(vote_average, 7.9)","(overview, In the smog-choked dystopian Los An...","(release_date, 1982-06-25)"

In [11]:
cols = []
for col in mymovies_df.columns:
    col = str(col)
    cols.append(col.lower())
mymovies_df.columns = cols
cols

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13']

In [12]:
mymovies_df =mymovies_df.rename(columns = {'0': 'popularity', '1': 'vote_count', '2': 'video' , '3': 'poster_path', '4': 'id' , '5': 'adult' , '6': 'backdrop_path' , '7': 'original_language', '8': 'original_title', '9': 'genre_ids' , '10': 'title' , '11': 'vote_average' , '12': 'overview' , '13': 'release_date'})

In [13]:
mymovies_df

,popularity,vote_count,video,poster_path,id,adult,backdrop_path,original_language,original_title,genre_ids,title,vote_average,overview,release_date
0,"(popularity, 454.192)","(vote_count, 1229)","(video, False)","(poster_path, /db32LaOibwEliAmSL2jjDF6oDdj.jpg)","(id, 181812)","(adult, False)","(backdrop_path, /dCB7d4l0mfpsISZvr6aPE2z5QF6.jpg)","(original_language, en)","(original_title, Star Wars: The Rise of Skywal...","(genre_ids, [28, 12, 878])","(title, Star Wars: The Rise of Skywalker)","(vote_average, 6.7)","(overview, The surviving Resistance faces the ...","(release_date, 2019-12-18)"
1,"(popularity, 472.09)","(vote_count, 1489)","(video, False)","(poster_path, /xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg)","(id, 419704)","(adult, False)","(backdrop_path, /p3TCqUDoVsrIm8fHK9KOTfWnDjZ.jpg)","(original_language, en)","(original_title, Ad Astra)","(genre_ids, [12, 18, 9648, 878, 53])","(title, Ad Astra)","(vote_average, 6)","(overview, The near future, a time when both h...","(release_date, 2019-09-17)"
2,"(popularity, 341.325)","(vote_count, 56)","(video, False)","(poster_path, /2MwpeDrI7RbgD6bipT31kpMZe9u.jpg)","(id, 449924)","(adult, False)","(backdrop_path, /ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg)","(original_language, cn)","(original_title, 葉問4)","(genre_ids, [28, 18, 36])","(title, Ip Man 4: The Finale)","(vote_average, 6.1)","(overview, Ip Man 4 is an upcoming Hong Kong b...","(release_date, 2019-12-20)"
3,"(popularity, 271.823)","(vote_count, 6940)","(video, False)","(poster_path, /udDclJoHjfjb8Ekgsd4FDteOkCU.jpg)","(id, 475557)","(adult, False)","(backdrop_path, /n6bUvigpRFqSwmPp1m2YADdbRBc.jpg)","(original_language, en)","(original_title, Joker)","(genre_ids, [80, 18, 53])","(title, Joker)","(vote_average, 8.3)","(overview, During the 1980s, a failed stand-up...","(release_date, 2019-10-02)"
4,"(popularity, 280.669)","(vote_count, 551)","(video, False)","(poster_path, /jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg)","(id, 512200)","(adult, False)","(backdrop_path, /zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg)","(original_language, en)","(original_title, Jumanji: The Next Level)","(genre_ids, [28, 12, 35, 14])","(title, Jumanji: The Next Level)","(vote_average, 6.7)","(overview, As the gang return to Jumanji to re...","(release_date, 2019-12-04)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975,"(popularity, 11.028)","(id, 261023)","(video, False)","(vote_count, 2160)","(vote_average, 6.4)","(title, Black Mass)","(release_date, 2015-09-04)","(original_language, en)","(original_title, Black Mass)","(genre_ids, [18, 80])","(backdrop_path, /fop31RWFi9sVL0xK5hAJGh7Fwkz.jpg)","(adult, False)","(overview, The true story of Whitey Bulger, th...","(poster_path, /nSbpuyd2UySuW7kaoXzYUfes1Bl.jpg)"
1976,"(popularity, 13.6)","(vote_count, 408)","(video, False)","(poster_path, /87OBsb8shf4FsBTGiEVsGwQeRFi.jpg)","(id, 9822)","(adult, False)","(backdrop_path, /auvJMRsnB46nh9I1rrXVp0MNshW.jpg)","(original_language, en)","(original_title, Mighty Joe Young)","(genre_ids, [28, 12, 14, 10751])","(title, Mighty Joe Young)","(vote_average, 6)","(overview, As a child living in Africa, Jill Y...","(release_date, 1998-12-25)"
1977,"(popularity, 19.452)","(vote_count, 210)","(video, False)","(poster_path, /wZGnnA9TVbZL81T9at8eHnZoCq4.jpg)","(id, 399173)","(adult, False)","(backdrop_path, /j4eGK1WH9YZWoDNDM9mAsF3mhLx.jpg)","(original_language, en)","(original_title, The Assignment)","(genre_ids, [28, 80, 53])","(title, The Assignment)","(vote_average, 5)","(overview, Ace assassin Frank Kitchen is doubl...","(release_date, 2016-04-27)"
1978,"(popularity, 11.534)","(vote_count, 876)","(video, False)","(poster_path, /oDJyDX11HW4j565vUjmFagKxDTQ.jpg)","(id, 8963)","(adult, False)","(backdrop_path, /27RVxku4mEr4fHW5oUu5KtSLO9D.jpg)","(original_language, en)","(original_title, Crimson Tide)","(genre_ids, [28, 53, 10752])","(title, Crimson Tide)","(vote_average, 7.1)","(overview, On a US nuclear missile sub, a youn...","(release_date, 1995-05-12)"
1979,"(popularity, 19.109)","(vote_count, 1256)","(video, False)","(poster_path, /ktPbjD6nYg5NxmeTt72Iqaw5GD0.jpg)","(id, 398181)","(adult, False)","(backdrop_path, /h4Lk8Cgfvlzz0hcnSJBTAOwNDia.jpg)","(original_language, en)","(original_title, You Were Never Really Here)","(genre_ids, [53])","(title, You Were Never Really Here)","(vote_average, 6.6)","(overview, A traumatised veteran, unafraid of ...","(release_date, 2017-11-08)"

In [14]:
pd.DataFrame(mymovies_df['popularity'].tolist(), index=mymovies_df.index)

               0        1
0     popularity  454.192
1     popularity  472.090
2     popularity  341.325
3     popularity  271.823
4     popularity  280.669
...          ...      ...
1975  popularity   11.028
1976  popularity   13.600
1977  popularity   19.452
1978  popularity   11.534
1979  popularity   19.109

[1980 rows x 2 columns]

In [15]:
pd.DataFrame(mymovies_df['vote_count'].tolist(), index=mymovies_df.index)

               0       1
0     vote_count    1229
1     vote_count    1489
2     vote_count      56
3     vote_count    6940
4     vote_count     551
...          ...     ...
1975          id  261023
1976  vote_count     408
1977  vote_count     210
1978  vote_count     876
1979  vote_count    1256

[1980 rows x 2 columns]

In [16]:
popularity = []

for i in mymovies_df['popularity']:
    pop1, pop2 = i
    popularity.append(pop2)
    
    pop_col_df = pd.DataFrame(popularity)
        


    pop_col_df = pop_col_df.rename(columns = {0 : "popularity"})

In [17]:
vote_count = []

for i in mymovies_df['vote_count']:
    pop1, pop2 = i
    vote_count.append(pop2)
    
    vote_count_df= pd.DataFrame(vote_count)
    
    vote_count_df = vote_count_df.rename(columns = {0 : "vote_count"})
    

#vote_count_df

In [18]:
video = []

for i in mymovies_df['video']:
    pop1, pop2 = i
    video.append(pop2)
    
    video_df = pd.DataFrame(video)
    
    video_df = video_df.rename(columns = {0 : "video"})
    
#video_df

In [19]:
poster_path = []

for i in mymovies_df['poster_path']:
    pop1, pop2 = i
    poster_path.append(pop2)
    
    poster_path_df = pd.DataFrame(poster_path)
    
    poster_path_df = poster_path_df.rename(columns = {0 : "poster_path"})
    
#poster_path_df

In [20]:
id = []

for i in mymovies_df['id']:
    pop1, pop2 = i
    id.append(pop2)
    
    id_df = pd.DataFrame(id)
    
    id_df = id_df.rename(columns = {0 : "id"})
    

#id_df

In [21]:
adult = []

for i in mymovies_df['adult']:
    pop1, pop2 = i
    adult.append(pop2)
    
    adult_df = pd.DataFrame(adult)
    
    adult_df = adult_df.rename(columns = {0 : "adult"})
    
    adult_df.replace(['Joker', 'Star Wars'], False, inplace=True)
    

#adult_df

In [22]:
backdrop_path = []

for i in mymovies_df['backdrop_path']:
    pop1, pop2 = i
    backdrop_path.append(pop2)
    
    backdrop_path_df = pd.DataFrame(backdrop_path)
    
    backdrop_path_df = backdrop_path_df.rename(columns = {0 : "backdrop_path"})
    

#backdrop_path_df

In [23]:
original_language = []

for i in mymovies_df['original_language']:
    pop1, pop2 = i
    original_language.append(pop2)
    
    original_language_df = pd.DataFrame(original_language)
    
    original_language_df = original_language_df.rename(columns = {0 : "original_language"})

original_language_df.count()

original_language    1980
dtype: int64

In [25]:
original_title = []

for i in mymovies_df['original_title']:
    pop1, pop2 = i
    original_title.append(pop2)
    
    original_title_df = pd.DataFrame(original_title)
    
    original_title_df = original_title_df.rename(columns = {0 : "original_title"})

original_title_df.count()

original_title    1979
dtype: int64

In [26]:
title = []

for i in mymovies_df['title']:
    pop1, pop2 = i
    title.append(pop2)
    
    title_df = pd.DataFrame(title)
    
    title_df = title_df.rename(columns = {0 : "title"})
    
title_df.count()

title    1978
dtype: int64

In [25]:
vote_average = []

for i in mymovies_df['vote_average']:
    pop1, pop2 = i
    vote_average.append(pop2)
    
    vote_average_df = pd.DataFrame(vote_average)
    
    vote_average_df = vote_average_df.rename(columns = {0 : "vote_average"})
    
    vote_average_df.replace(['Joker', 'Star Wars'], False, inplace=True)
    
    vote_average_df.replace( False, np.nan, inplace=True)
    
    
    
    
    
vote_average_df.count()

vote_average    1574
dtype: int64

In [21]:
overview = []

for i in mymovies_df['overview']:
    pop1, pop2 = i
    overview.append(pop2)
    
    overview_df = pd.DataFrame(overview)
    
    overview_df = overview_df.rename(columns = {0 : "overview"})
    
#overview_df

In [24]:
overview_df.count()

overview    1980
dtype: int64

In [ ]:
# release_date = []

# for i in mymovies_df['release_date']:
#     pop1, pop2 = i
#     release_date.append(pop2)
    
#     release_date_df = pd.DataFrame(release_date)
    
#     release_date_df = release_date_df.rename(columns = {0 : "release_date"})

In [41]:
release_date_df = pd.DataFrame(mymovies_df['release_date'].tolist(), index=mymovies_df.index)

release_date_df

                 0                                 1
0     release_date                        2019-12-18
1     release_date                        2019-09-17
2     release_date                        2019-12-20
3     release_date                        2019-10-02
4     release_date                        2019-12-04
...            ...                               ...
1975   poster_path  /nSbpuyd2UySuW7kaoXzYUfes1Bl.jpg
1976  release_date                        1998-12-25
1977  release_date                        2016-04-27
1978  release_date                        1995-05-12
1979  release_date                        2017-11-08

[1980 rows x 2 columns]

In [ ]:
release_date_df.replace('/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg', '2019-10-02', inplace=True)

release_date_df.replace('/btTdmkgIvOi0FFip1sPuZI2oQG6.jpg', '1977-05-25', inplace=True)

In [ ]:
release_date_df.count()

In [ ]:
movie_results = pd.concat([pop_col_df, vote_count_df, video_df, poster_path_df, id_df, adult_df, backdrop_path_df, original_language_df, 
                    original_title_df, title_df, vote_average_df, overview_df, release_date_df], axis = 1)

In [ ]:
movie_results

In [ ]:
cols = []
for col in movie_results.columns:
    col = str(col)
    cols.append(col.lower())
movie_results.columns = cols
cols

In [ ]:

rds_connection_string = "postgres:Dbadmin@localhost:5432/ODBM_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [ ]:
engine.table_names()

In [ ]:
movie_results.to_sql(name='movies', con=engine, if_exists='append', index=False)